version: '3.1'
services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: example
            MYSQL_ROOT_PASSWORD: example
            MYSQL_USER: example
        volumes:
            - ./db:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
        - 8080:80
        environment:
        - PMA_ARBITRARY=1
        depends_on:
            - db 
